# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "kamailio-infra-tfstate"
    dynamodb_table = "tf-locks"
    encrypt        = true
    key            = "envs/prod/tf.tfstate"
    region         = "eu-central-1"
  }
}
