---
- name: ensure packages are installed
  ansible.builtin.apt:
    name: "{{ package }}"
    state: latest
  loop: "{{ common_pkgs }}"
  loop_control:
    loop_var: package
  become: true

- name: ssh authorized_keys
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ item }}"
    state: present
  loop: "{{ common_sshkeys | default([]) }}"

- name: Download tmux.conf
  ansible.builtin.get_url:
    url: "{{ __common_gh_base }}/.tmux.conf"
    dest: "{{ ansible_facts.user_dir }}/.tmux.conf"
    mode: '0640'

- name: XTerm info for ghostty
  ansible.builtin.copy:
    src: xterm-ghostty
    dest: /usr/share/terminfo/x/xterm-ghostty
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Checkout jenkins-jobs configs repository
  ansible.builtin.git: # noqa: latest[git] partial-become
    repo: "{{ common_kamailio_deb_jenkins_repo }}"
    dest: "{{ __common_jenkins_jobs_cfg_dir }}"
  tags:
    - html
    - jjb

- name: perms for group access
  ansible.builtin.file:
    path: "{{ ansible_facts.user_dir }}"
    state: directory
    mode: '0750'
  become: true

- name: Ensure checkout dirs 0750
  ansible.builtin.command: find -type d ! -perm 0750 -exec chmod 0750 {} \;
  args:
    chdir: "{{ __common_jenkins_jobs_cfg_dir }}"
  changed_when: true
  tags:
    - jjb
  become: true

- name: Ensure files 0640
  ansible.builtin.command: find . -type f ! -perm 0640 -exec chmod 0640 {} \;
  args:
    chdir: "{{ __common_jenkins_jobs_cfg_dir }}"
  changed_when: true
  tags:
    - jjb
  become: true

- name: Ensure scripts files 0750
  ansible.builtin.command: find {{ item }} -type f ! -perm 0750 -exec chmod 0750 {} \;
  args:
    chdir: "{{ __common_jenkins_jobs_cfg_dir }}"
  loop:
    - scripts
    - jjb/jenkins-jobs-wrapper
  changed_when: true
  tags:
    - jjb
  become: true

- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ __common_hostname }}"
  when: __common_hostname | regex_search('.*\.kamailio.org$') is defined
  become: yes
